---
- name: Update Package Cache
  package:
    name: '*'
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Update Package Cache
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install Common Dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - unzip
